# Day - 1

## Variables 

A variable is a memory location where we can store value or it is a container to store data.


## Rules for variable names
* names can not start with a number
* names can not contain spaces, use _ intead
* names can not contain any of these symbols:

      :'",<>/?|\!@#%^&*~-+

In [1]:
# Initialize x
x = 5

In [2]:
print(x)

5


In [3]:
# Initialize y
y = 10

In [4]:
print(y)

10


In [5]:
# Assign the sum to z
z = x + y

In [6]:
print(z)

15


In [7]:
# Let us ask from the user







Just like print we have a function `type()` which tells us about the datatype of the variable.

In [8]:
type(x)

int

In [9]:
my_input = input()
type(my_input)

12345


str

## Strings

Strings are used in Python to record text information. Strings are sequence of characters enclosed by “...” or ‘…’ (double quotes or single quotes)

### String Declaration

In [10]:
# Single Word
print("Alien")

Alien


In [11]:
#Sentence
print('Hello Alien')

Hello Alien


### String Indexing

In [12]:
s = "Hello Alien"

In [13]:
print(s)

Hello Alien


In [14]:
s[0]

'H'

In [15]:
s[1]

'e'

In [16]:
s[2]

'l'

In [17]:
# Now in reverse
s[-1]

'n'

In [18]:
s[-2]

'e'

In [19]:
s="Spaceonova"

In [20]:
# 5th letter from the start


## Lists

Lists are constructed with brackets [ ] and commas separating every element in the list.

In [21]:
my_list = ['a','b','c']
print(my_list)
type(my_list)

['a', 'b', 'c']


list

In [22]:
my_list[0]

'a'

In [23]:
my_list[1]

'b'

In [24]:
my_list[-1]

'c'

## What is the difference then?

Let's us take an example where we did a typo and instead of 'Hello Alien' you wrote 'Xello Alien'.

In [25]:
s="Xello Alien"

In [26]:
s[0]='H'

TypeError: 'str' object does not support item assignment

In [27]:
l=['a',5,'c']
print(l)

['a', 5, 'c']


In [28]:
l[1]='f'

In [29]:
l

['a', 'f', 'c']

Therefore we understood that strings are [immutable](https://www.google.com/search?q=immutable+meaning) and lists are mutable.

## Conditional Statements

Let us first see a few expressions

In [30]:
5 >= 6

False

In [31]:
4 < 9

True

In [32]:
2 == 1+1

True

In [33]:
4 != 5

True

### If and else

In [34]:
velocity = int(input('Enter velocity: '))

Enter velocity: 20


In [35]:
if velocity > 11.2:
    print('Rocket will escape!')

Rocket will escape!


In [36]:
velocity = 20
if velocity > 11.2:
    print('Rocket will escape!')
else:
    print('Rocket will crash')

Rocket will escape!


In [37]:
velocity = 20
if velocity > 11.2: #greater than 11.2
    print('Rocket will escape!')
    
elif velocity>5:   #less than 11.2 but greater than 5 
    print('Rocket will rotate around Earth!')
    
else:
    print('Rocket will crash')

Rocket will escape!


## For Loops

Here's the general format for a <code>for</code> loop in Python:

    for item in object:
        statements to do stuff

In [38]:
for i in range(100):
    print("Hello Alien")

Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hello Alien
Hell

In [39]:
l = [1,2,3,4,5]

In [40]:
for i in l:
    print(i)

1
2
3
4
5


In [41]:
list(range(20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [42]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


### Numpy

Let us try doubling each element of the list.

In [44]:
l1=[1,2,3,4,5]
print(l1*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


Numpy to the rescue 🚀

In [45]:
import numpy as np

In [46]:
l=np.array([1,2,3,4,5,6])

In [47]:
l*2

array([ 2,  4,  6,  8, 10, 12])

In [48]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[11,12,13],[14,15,16],[17,18,19]])

In [49]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [51]:
c=[a,b]
c

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])]

In [52]:
np.mean(c,axis=0)

array([[ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

In [53]:
(a+b)/2

array([[ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

---